version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - 4000:8080
  nginx-app:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 5555:80