version: "3"
services:
  cra:
    build:
      context: .
      dockerfile: cra.Dockerfile 
    ports:
      - 3333:80
  router:
    build:
      context: .
      dockerfile: router.Dockerfile
    ports:
      - 4444:80